document.querySelectorAll(".city.moscow").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Московской областью"));
document.querySelectorAll(".city.kaluga").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Калужской областью"));
document.querySelectorAll(".city.bryansk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за  Брянской областью"));
document.querySelectorAll(".city.smolensk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Смоленской областью "));
document.querySelectorAll(".city.tver").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Тверской областью"));
document.querySelectorAll(".city.yaroslavl").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Ярославской областью"));
document.querySelectorAll(".city.vladimir").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Владимирской областью"));
document.querySelectorAll(".city.kineshma").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Ивановской областью"));
document.querySelectorAll(".city.novgorod").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Новгородской областью"));
document.querySelectorAll(".city.pskov").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Псковской областью"));
document.querySelectorAll(".city.spb").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Ленинградской областью"));
document.querySelectorAll(".city.kaliningrad").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Калининградской областью"));
document.querySelectorAll(".city.murmansk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Мурманской областью"));
document.querySelectorAll(".city.karelia").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Карелией "));
document.querySelectorAll(".city.arkhangelsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Архангельской областью"));
document.querySelectorAll(".city.vologda").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Вологодской областью"));
document.querySelectorAll(".city.kursk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Курской областью"));
document.querySelectorAll(".city.orel").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Орловской областью"));
document.querySelectorAll(".city.tula").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Тульской областью"));
document.querySelectorAll(".city.ryazan").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Рязанской областью"));
document.querySelectorAll(".city.lipeck").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Липецкой областью"));
document.querySelectorAll(".city.belgorod").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Белгородская область"));
document.querySelectorAll(".city.voronezh").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Воронежской областью"));
document.querySelectorAll(".city.tambov").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Тамбовской областью"));
document.querySelectorAll(".city.penza").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Пензенской областью"));
document.querySelectorAll(".city.saransk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Мордовией"));
document.querySelectorAll(".city.nizhniyNovgorod").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Нижегородской областью"));
document.querySelectorAll(".city.kostroma").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Костромской областью"));
document.querySelectorAll(".city.cheboksari").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Чувашией"));
document.querySelectorAll(".city.yoshkarOla").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Марий Эл"));
document.querySelectorAll(".city.kirov").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Кировской областью"));
document.querySelectorAll(".city.komi").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Коми"));
document.querySelectorAll(".city.rostovNaDonu").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Ростовской областью"));
document.querySelectorAll(".city.volgograd").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Волгоградской областью"));
document.querySelectorAll(".city.krasnodar").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Краснодарским краем"));
document.querySelectorAll(".city.maykop").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Адыгея"));
document.querySelectorAll(".city.simferopol").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Крым"));
document.querySelectorAll(".city.kalmikia").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Калмыкия"));
document.querySelectorAll(".city.ahtubinsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Астраханской областью"));
document.querySelectorAll(".city.stavropol").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Ставропольским краем"));
document.querySelectorAll(".city.cherkevsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Карачаево-Черкесской республикой"));
document.querySelectorAll(".city.mahachkala").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Дагестан"));
document.querySelectorAll(".city.groznyi").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Чеченской республикой"));
document.querySelectorAll(".city.magas").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Ингушетия"));
document.querySelectorAll(".city.vladikavkaz").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Северная осетия"));
document.querySelectorAll(".city.nalchik").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Кабардино-Балкарской республикой"));
document.querySelectorAll(".city.saratov").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Саратовская область"));
document.querySelectorAll(".city.ulianovsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Ульяновской областью"));
document.querySelectorAll(".city.samara").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Самарской областью"));
document.querySelectorAll(".city.tatarstan").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Татарстан"));
document.querySelectorAll(".city.izhevsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Удмуртия"));
document.querySelectorAll(".city.orenburg").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Оренбургской областью"));
document.querySelectorAll(".city.bashkortostan").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Башкортостан"));
document.querySelectorAll(".city.chelyabinsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Челябинской областью"));
document.querySelectorAll(".city.perm").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Пермская область"));
document.querySelectorAll(".city.ekaterinburg").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Свердловской областью"));
document.querySelectorAll(".city.kurgan").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Курганской областью"));
document.querySelectorAll(".city.HMAO").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Ханта-Мансийским автономным округом"));
document.querySelectorAll(".city.tyumen").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Тюменской областью"));
document.querySelectorAll(".city.omsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Омской областью"));
document.querySelectorAll(".city.YNAO").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Ямало-Ненецким автономным округом"));
document.querySelectorAll(".city.tomsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Томской областью"));
document.querySelectorAll(".city.novosibirsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Новосибирской областью"));
document.querySelectorAll(".city.altayskiyKray").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Алтайским краем"));
document.querySelectorAll(".city.krasnoyarsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Красноярским краем"));
document.querySelectorAll(".city.kemerovo").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Кемеровской областью"));
document.querySelectorAll(".city.altay").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Алтай"));
document.querySelectorAll(".city.hakasiya").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Хакасия"));
document.querySelectorAll(".city.tiva").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Тыва"));
document.querySelectorAll(".city.irkutsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Иркутской областью"));
document.querySelectorAll(".city.buryatia").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Бурятия"));
document.querySelectorAll(".city.saha").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за республикой Саха"));
document.querySelectorAll(".city.zabaykalsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Забайкальский край"));
document.querySelectorAll(".city.amurskaya").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Амурской областью"));
document.querySelectorAll(".city.evreyskaya").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Еврейской автономной областью"));
document.querySelectorAll(".city.primorskiy").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Приморским краем"));
document.querySelectorAll(".city.habarovsk").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Хабаровским краем "));
document.querySelectorAll(".city.sahalin").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете Сахалинской областью"));
document.querySelectorAll(".city.chao").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Чукотским автономным округом"));
document.querySelectorAll(".city.magadan").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Магаданской областью"));
document.querySelectorAll(".city.kamchatka").forEach(el => el.addEventListener("mouseover", e => document.getElementById('output').innerHTML = "Вы наблюдаете за Камчатским краем"));
document.querySelectorAll('.outside').forEach(el => el.addEventListener('mouserover', e => document.getElementById('output').innerHTML = "Наведите курсор на карту"));